<<<<<<< HEAD
# Generated by Django 5.2.4 on 2025-08-05 12:37
=======
# Generated by Django 5.2.4 on 2025-08-06 11:08
>>>>>>> master

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0002_alter_article_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at']},
        ),
    ]
