# Generated by Django 4.2.16 on 2024-10-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopets_platform', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ['posted_at']},
        ),
        migrations.AddField(
            model_name='pet',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
