# Generated by Django 4.2.16 on 2024-10-11 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopets_platform', '0002_alter_pet_options_pet_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='slug',
        ),
    ]
