# Generated by Django 4.2.16 on 2024-10-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopets_platform', '0004_adoptionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='city',
            field=models.CharField(default='Default City', max_length=100),
        ),
        migrations.AddField(
            model_name='pet',
            name='country',
            field=models.CharField(default='Default Country', max_length=100),
        ),
    ]
