# Generated by Django 4.2.16 on 2024-10-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopets_platform', '0006_alter_adoptionrequest_options_adoptionrequest_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ['-posted_at']},
        ),
        migrations.AlterField(
            model_name='pet',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pet',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pet',
            name='photo',
            field=models.ImageField(upload_to='static/images/pet_photos/'),
        ),
    ]
