<<<<<<< HEAD
# Generated by Django 5.2.4 on 2025-08-05 12:37
=======
# Generated by Django 5.2.4 on 2025-08-06 11:08
>>>>>>> master

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopets_platform', '0008_pet_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adoptionrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=100)),
                ('sender_email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
<<<<<<< HEAD
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='adopets_platform.pet')),
=======
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_messages', to='adopets_platform.pet')),
>>>>>>> master
            ],
        ),
    ]
